server:
  port:
    8001

spring:
  application:
    name: sensor-data-interpreter
  kafka:
    auto-offset-reset: latest
    bootstrap-servers: localhost:9092
    group-id: consumer-group
    topic:
      name: sensor_topic
    concurrency-number: 4
  data:
    mongodb:
      database: sensor
      uri: mongodb://localhost:27017
      auto-index-creation: true
  datasource:
    url: jdbc:postgresql://localhost:5432/sensor
    driverClassName: org.postgresql.Driver
    username: postgres
    password: postgres
    hikari:
      maximum-pool-size: 100
      auto-commit: false
      pool-name: SensorHikariPool
    initialization-mode: always
  jpa:
    show-sql: false
    hibernate:
        ddl-auto: update
        format-sql: true
        generate_statistics: true
        use_query_cache: true

scheduled:
  database-saver-in-ms: 1000

executor-service:
  fixed-thread-pool-size: 100

default-power-value: 2
